### ISSUE TITLE
Mc2For usage

### ISSUE THREAD

**Issue by infinity77** [Sable/Mc2For#6]
Hi,

I am not sure whether this project is still alive or not. In any case, I gave it a try but I have no clue how exactly it needs to be used. My attempts below, followed by interesting Java errors:

    C:\Users\USER>java -jar Mc2For.jar -nocheck my_mfile.m
    Exception in thread "main" java.lang.IllegalArgumentException: No enum constant natlab.tame.classes.reference.PrimitiveClassReference.double
            at java.lang.Enum.valueOf(Unknown Source)
            at natlab.tame.classes.reference.PrimitiveClassReference.valueOf(PrimitiveClassReference.java:23)
            at natlab.tame.BasicTamerTool.getListOfInputValues(BasicTamerTool.java:112)
            at natlab.tame.BasicTamerTool.analyze(BasicTamerTool.java:75)
            at natlab.backends.Fortran.codegen_readable.Main_readable.compile(Main_readable.java:183)
            at natlab.Main.main(Main.java:127)

    C:\Users\USER>java -jar Mc2For.jar -codegen my_mfile.m
    Exception in thread "main" java.lang.IllegalArgumentException: No enum constant natlab.tame.classes.reference.PrimitiveClassReference.double
            at java.lang.Enum.valueOf(Unknown Source)
            at natlab.tame.classes.reference.PrimitiveClassReference.valueOf(PrimitiveClassReference.java:23)
            at natlab.tame.BasicTamerTool.getListOfInputValues(BasicTamerTool.java:112)
            at natlab.tame.BasicTamerTool.analyze(BasicTamerTool.java:75)
            at natlab.backends.Fortran.codegen_readable.Main_readable.compile(Main_readable.java:183)
            at natlab.Main.main(Main.java:127)

I am sure I am missing something, any guidance would be most welcome. Thank you.

**Comment by isbadawi** [comment]
I don't believe this project is maintained anymore.

As far as I can tell, you need to specify `-args` to give the types of the input arguments to your function, for example `-args 'DOUBLE&1*1&REAL'` (type & shape & real or complex). It looks like the default is broken.

**Comment by peterukk** [comment]
I couldn't get it to work either. Shame
